-- Expands the shared brand catalogue well beyond the original car-only
-- seed (0008): adds motorcycle, scooter, EV two-wheeler and light-commercial
-- makes, which is most of what actually gets leased in Kerala. KTM only
-- existed here because a lister typed it and findBrandId auto-created it.
--
-- Model names are NOT stored in this table — vehicles.model is free text and
-- the Model picker suggests client-side from lib/data/india-vehicle-brands.json,
-- which this list is generated from so the two stay in step.
--
-- Existing rows are preserved; only brands not already present by slug are
-- inserted.
insert into public.brands (name, slug)
values
  ('Maruti Suzuki', 'maruti-suzuki'),
  ('Hyundai', 'hyundai'),
  ('Tata', 'tata'),
  ('Mahindra', 'mahindra'),
  ('Kia', 'kia'),
  ('Toyota', 'toyota'),
  ('Honda', 'honda'),
  ('Renault', 'renault'),
  ('Nissan', 'nissan'),
  ('Volkswagen', 'volkswagen'),
  ('Skoda', 'skoda'),
  ('MG', 'mg'),
  ('Citroen', 'citroen'),
  ('BYD', 'byd'),
  ('Jeep', 'jeep'),
  ('BMW', 'bmw'),
  ('Mercedes-Benz', 'mercedes-benz'),
  ('Audi', 'audi'),
  ('Volvo', 'volvo'),
  ('Land Rover', 'land-rover'),
  ('Lexus', 'lexus'),
  ('Porsche', 'porsche'),
  ('Jaguar', 'jaguar'),
  ('Mini', 'mini'),
  ('Isuzu', 'isuzu'),
  ('Force Motors', 'force-motors'),
  ('Mitsubishi', 'mitsubishi'),
  ('Ford', 'ford'),
  ('Chevrolet', 'chevrolet'),
  ('Fiat', 'fiat'),
  ('Datsun', 'datsun'),
  ('Ashok Leyland', 'ashok-leyland'),
  ('Eicher', 'eicher'),
  ('Tesla', 'tesla'),
  ('Royal Enfield', 'royal-enfield'),
  ('KTM', 'ktm'),
  ('Bajaj', 'bajaj'),
  ('TVS', 'tvs'),
  ('Hero', 'hero'),
  ('Yamaha', 'yamaha'),
  ('Suzuki', 'suzuki'),
  ('Jawa', 'jawa'),
  ('Yezdi', 'yezdi'),
  ('Harley-Davidson', 'harley-davidson'),
  ('Triumph', 'triumph'),
  ('Kawasaki', 'kawasaki'),
  ('BMW Motorrad', 'bmw-motorrad'),
  ('Ducati', 'ducati'),
  ('Aprilia', 'aprilia'),
  ('Vespa', 'vespa'),
  ('Benelli', 'benelli'),
  ('CFMoto', 'cfmoto'),
  ('Husqvarna', 'husqvarna'),
  ('Keeway', 'keeway'),
  ('QJ Motor', 'qj-motor'),
  ('Zontes', 'zontes'),
  ('Moto Morini', 'moto-morini'),
  ('Ather', 'ather'),
  ('Ola Electric', 'ola-electric'),
  ('Ultraviolette', 'ultraviolette'),
  ('Revolt', 'revolt'),
  ('River', 'river'),
  ('Matter', 'matter'),
  ('Tork Motors', 'tork-motors'),
  ('Ampere', 'ampere'),
  ('Okinawa', 'okinawa'),
  ('Simple Energy', 'simple-energy'),
  ('Bounce', 'bounce'),
  ('BGauss', 'bgauss'),
  ('Kinetic Green', 'kinetic-green'),
  ('PURE EV', 'pure-ev'),
  ('Komaki', 'komaki'),
  ('Hop Electric', 'hop-electric')
on conflict (slug) do nothing;
