-- Second pass on the brand catalogue (see 0031): adds the commercial and
-- equipment side — pickups/LCVs, three-wheelers (Piaggio Ape, Atul), tippers,
-- construction and earthmoving makes (JCB, Tata Hitachi, CAT, Komatsu, SANY)
-- and tractors. All of these get leased in Kerala and none were selectable
-- before, so a lister had to type the make as free text and rely on
-- findBrandId auto-creating it — which is how typo brands like maruthi
-- appeared in the first place.
--
-- Regenerated from the full lib/data/india-vehicle-brands.json rather than
-- just the delta, so this file and that file are provably the same list.
-- "on conflict do nothing" makes it idempotent against everything 0008 and
-- 0031 already inserted.
insert into public.brands (name, slug)
values
  ('Maruti Suzuki', 'maruti-suzuki'),
  ('Hyundai', 'hyundai'),
  ('Tata', 'tata'),
  ('Mahindra', 'mahindra'),
  ('Kia', 'kia'),
  ('Toyota', 'toyota'),
  ('Honda', 'honda'),
  ('Renault', 'renault'),
  ('Nissan', 'nissan'),
  ('Volkswagen', 'volkswagen'),
  ('Skoda', 'skoda'),
  ('MG', 'mg'),
  ('Citroen', 'citroen'),
  ('BYD', 'byd'),
  ('Jeep', 'jeep'),
  ('BMW', 'bmw'),
  ('Mercedes-Benz', 'mercedes-benz'),
  ('Audi', 'audi'),
  ('Volvo', 'volvo'),
  ('Land Rover', 'land-rover'),
  ('Lexus', 'lexus'),
  ('Porsche', 'porsche'),
  ('Jaguar', 'jaguar'),
  ('Mini', 'mini'),
  ('Isuzu', 'isuzu'),
  ('Force Motors', 'force-motors'),
  ('Mitsubishi', 'mitsubishi'),
  ('Ford', 'ford'),
  ('Chevrolet', 'chevrolet'),
  ('Fiat', 'fiat'),
  ('Datsun', 'datsun'),
  ('Ashok Leyland', 'ashok-leyland'),
  ('Eicher', 'eicher'),
  ('Tesla', 'tesla'),
  ('Royal Enfield', 'royal-enfield'),
  ('KTM', 'ktm'),
  ('Bajaj', 'bajaj'),
  ('TVS', 'tvs'),
  ('Hero', 'hero'),
  ('Yamaha', 'yamaha'),
  ('Suzuki', 'suzuki'),
  ('Jawa', 'jawa'),
  ('Yezdi', 'yezdi'),
  ('Harley-Davidson', 'harley-davidson'),
  ('Triumph', 'triumph'),
  ('Kawasaki', 'kawasaki'),
  ('BMW Motorrad', 'bmw-motorrad'),
  ('Ducati', 'ducati'),
  ('Aprilia', 'aprilia'),
  ('Vespa', 'vespa'),
  ('Benelli', 'benelli'),
  ('CFMoto', 'cfmoto'),
  ('Husqvarna', 'husqvarna'),
  ('Keeway', 'keeway'),
  ('QJ Motor', 'qj-motor'),
  ('Zontes', 'zontes'),
  ('Moto Morini', 'moto-morini'),
  ('Ather', 'ather'),
  ('Ola Electric', 'ola-electric'),
  ('Ultraviolette', 'ultraviolette'),
  ('Revolt', 'revolt'),
  ('River', 'river'),
  ('Matter', 'matter'),
  ('Tork Motors', 'tork-motors'),
  ('Ampere', 'ampere'),
  ('Okinawa', 'okinawa'),
  ('Simple Energy', 'simple-energy'),
  ('Bounce', 'bounce'),
  ('BGauss', 'bgauss'),
  ('Kinetic Green', 'kinetic-green'),
  ('PURE EV', 'pure-ev'),
  ('Komaki', 'komaki'),
  ('Hop Electric', 'hop-electric'),
  ('Piaggio', 'piaggio'),
  ('Atul Auto', 'atul-auto'),
  ('Euler Motors', 'euler-motors'),
  ('Montra Electric', 'montra-electric'),
  ('Switch Mobility', 'switch-mobility'),
  ('SML Isuzu', 'sml-isuzu'),
  ('Bharat Benz', 'bharat-benz'),
  ('JCB', 'jcb'),
  ('Tata Hitachi', 'tata-hitachi'),
  ('Caterpillar', 'caterpillar'),
  ('Komatsu', 'komatsu'),
  ('Hyundai Construction', 'hyundai-construction'),
  ('Volvo CE', 'volvo-ce'),
  ('Kobelco', 'kobelco'),
  ('SANY', 'sany'),
  ('CASE', 'case'),
  ('ACE', 'ace'),
  ('Escorts Kubota', 'escorts-kubota'),
  ('Bull Machines', 'bull-machines'),
  ('Ajax', 'ajax'),
  ('Schwing Stetter', 'schwing-stetter'),
  ('Mahindra Construction', 'mahindra-construction'),
  ('Sonalika', 'sonalika'),
  ('John Deere', 'john-deere'),
  ('Massey Ferguson', 'massey-ferguson'),
  ('New Holland', 'new-holland'),
  ('Swaraj', 'swaraj'),
  ('Kubota', 'kubota'),
  ('Farmtrac', 'farmtrac'),
  ('VST', 'vst')
on conflict (slug) do nothing;
